---
branches:
  only:
    - master
    - develop

language: node_js

matrix:
  include:
    - os: linux
      node_js: "6"
    - os: linux
      node_js: "7"
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "9"

before_install:
  - sudo apt-get install graphicsmagick

after_success:
  - npm run coveralls
