os: Visual Studio 2015
build: off
platform: x64
environment:
  matrix:
  - nodejs_version: "6"
  - nodejs_version: "7"
install:
  - appveyor DownloadFile http://downloads.sourceforge.net/graphicsmagick/GraphicsMagick-1.3.21-Q8-win32-dll.exe
  - GraphicsMagick-1.3.21-Q8-win32-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@latest
  - npm install
test_script:
  - npm test
